version: '3'

services:
  webApp:
    image: 128261723812/odds-web-backend
    hostname: webapp
    ports:
      - 8080:8123

  selenium_env:
    image: selenium/standalone-firefox:112.0
    hostname: selenium_env
    depends_on:
      - webApp

  data_source:
    image: 128261723812/oddsproducer:latest
    environment: 
      - driver_server=http://selenium_env:4444
      - consumer_server=http://webApp:8123/data
    depends_on:
      - selenium_env
    restart: always

  model_container:
    image: 128261723812/odds-model:latest
    hostname: model
    depends_on:
      - webApp
      - data_source
    restart: on-failure
